---
kind: pipeline
type: docker
name: ci

trigger:
  ref:
    - refs/heads/trunk

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: root_home
    host:
      path: /root

steps:
  - name: build
    image: 324181518966.dkr.ecr.us-west-2.amazonaws.com/docker-builder:55
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: root_home
        path: /root
    
    commands:
      - make push
