---
kind: pipeline
type: docker
name: release-amd64

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    - refs/heads/trunk

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: root_home
    host:
      path: /root

steps:
  - name: build
    image: 324181518966.dkr.ecr.us-west-2.amazonaws.com/docker-builder:83
    environment:
      docker_password:
        from_secret: docker_password
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: root_home
        path: /root
    
    commands:
      - make push

---

kind: pipeline
type: docker
name: release-arm64

platform:
  os: linux
  arch: arm64

trigger:
  ref:
    - refs/heads/trunk

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: root_home
    host:
      path: /root

steps:
  - name: build
    image: 324181518966.dkr.ecr.us-west-2.amazonaws.com/docker-builder:83
    environment:
      docker_password:
        from_secret: docker_password
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: root_home
        path: /root
    
    commands:
      - make push

---

kind: pipeline
type: docker
name: publish-manifest

trigger:
  ref:
    - refs/heads/trunk
    - refs/tags/**

depends_on: [ release-amd64, release-arm64 ]
steps:
  - name: stitch
    image: 324181518966.dkr.ecr.us-west-2.amazonaws.com/docker-builder:83
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: root_home
        path: /root

    commands:
      - make stitch
volumes:
    - name: docker_sock
      host:
        path: /var/run/docker.sock
    - name: root_home
      host:
        path: /root
